name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Enable required Google Cloud APIs'
      run: |
        gcloud services enable deploymentmanager.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}
        gcloud services enable secretmanager.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}
        gcloud services enable compute.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Deploy to Cloud Deployment Manager'
      run: |
        gcloud deployment-manager deployments update my-first-vm --config vm_template.yaml --project ${{ secrets.GCP_PROJECT_ID }} --set-properties="timestamp=$(date +%s)" || \
        gcloud deployment-manager deployments create my-first-vm --config vm_template.yaml --project ${{ secrets.GCP_PROJECT_ID }} --set-properties="timestamp=$(date +%s)"
